POST http://localhost:5555
Content-Type: application/json

// page: "hainarbeit | looneys"
{
    "name": "glen coden",
    "email": "info@simonmeyer.de",
    "content": "glen was here",
    "page": "",
    "admin_password": ""
}

###
